version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus.${ENV}.${ORGANIZATION}-${SERVER}.internal"
    env_file:
      - .env
    ports:
      - "${PROMETHEUS_PORT}:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  cadvisor:
    image: google/cadvisor:latest
    container_name: "cadvisor.${ENV}.${ORGANIZATION}-${SERVER}.internal"
    env_file:
      - .env
    ports:
      - "${CADVISOR_PORT}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: "redis.${ENV}.${ORGANIZATION}-${SERVER}.internal"
    env_file:
      - .env
    networks: 
      - internal-network

networks:
  internal-network:
    driver: overlay
    attachable: true
    name: 'development-internal-network'

volumes: 
  development-volume:
    name: 'development-volume'
    external: true
